### ISSUE TITLE
[feature request] use arxiv id instead of inspire citation key

### ISSUE THREAD

**Issue by pseyfert** [DavidMStraub/inspiretools#2]
I prefer using `\cite{1507.03414}` over `\cite{Aaij:2015tga}` and it seems to me, inspiretools could almost handle this, if [inspiretools/functions.py:71](https://github.com/DavidMStraub/inspiretools/blob/master/inspiretools/functions.py#L71) had `eprint` instead of `texkey` in the first occurance, haven't tried though.

**Comment by DavidMStraub** [comment]
Thanks for the suggestion. Fetching the bibtex entry given the eprint number is easy, but the entry returned by Inspire will still have the Inspire texkey as BibTeX key, so the bibliography will not compile ...

**Comment by pseyfert** [comment]
ah indeed, so an additional manipulation of the BibTeX key is needed.

**Comment by pseyfert** [comment]
closing all my cern related issues as won't-pursue-anymore / don't care anymore - regardless of status

**Comment by DavidMStraub** [comment]
I feel you :laughing:
