### ISSUE TITLE
blgtobib does not work when using the biber backend

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/inspiretools#4]
Make it work or find an alternative to using the blg file.

**Comment by musoke** [comment]
I didn't look into biber when I added blgtobib, so I'm not surprised to hear that it doesn't work.

**Comment by DavidMStraub** [comment]
Hi, I think I fixed it by modifying the regexp. The problem was that biber has something like

`[609] Utils.pm:149> WARN - I didn't find a database entry for 'x:y' (section 0)`

where bibtex would have

`Warning--I didn't find a database entry for "x:y"`
