### ISSUE TITLE
References not found -> probably change on INSPIRE's side

### ISSUE THREAD

**Issue by MartinJung1978** [DavidMStraub/inspiretools#6]
Hi,
blgtobib stopped working for me. For instance, I receive the message
INFO:inspiretools:Reference Urquijo:2006wd not found on INSPIRE!
while an entry exists that starts like
@article{Urquijo:2006wd,
    author = "Urquijo, P. and others", ...

I suspect that this is due to the recent changes on INSPIRE, but I can't be sure.
I'd appreciate if this could be fixed, I use your tool a lot :-)
Best, Martin

**Comment by DavidMStraub** [comment]
Hi! Are you using v0.2.1, that incorporates #5?

**Comment by MartinJung1978** [comment]
I installed v0.2.1, yes. Calling it, I can't find a version number though, to be 100% I'm calling the correct version.

**Comment by MartinJung1978** [comment]
Hi again, it turns out I had two versions installed in parallel and it called the wrong one, sorry about that. Now it works again...
