### ISSUE TITLE
New Inspire API

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/inspiretools#7]
This tool needs to be migrated to the [new Inspire API](https://github.com/inspirehep/rest-api-doc).

Any of the former contributors interested in giving it a shot? @dvandyk @musoke @michamos? Or users @MartinJung1978 @peterstangl @JasonAebischerGit?

Since I don't use Inspire regularly anymore, my motivation is limited. But adapting the `pyinspire.py` should be pretty straightforward. The `BeautifulSoup` stuff isn't necessary anymore as they now have a "proper" REST API.

**Comment by musoke** [comment]
I took a look at the new API.  It doesn't seem to have an easy way to search by texkey, which is what I'd be most interested in.  I might make an issue over there if I get a chance to look into it further.

**Comment by DavidMStraub** [comment]
This seems to work:

https://inspirehep.net/api/literature?q=texkey:Aebischer:2019mlg

**Comment by musoke** [comment]
Perfect.  Where did you find that information?  I think I'm missing some docs.

**Comment by DavidMStraub** [comment]
Trial and error :wink:
